#!/usr/bin/env bun
/**
 * Generate the committed, self-contained Node-target validator shim under the
 * `ce:review` skill.
 *
 * The shim (`skills/ce-review/scripts/validate-review.mjs`) is a packaging
 * compatibility layer: shipped skill layouts cannot all rely on the npm CLI or
 * `dist/`, so the committed bundle is invoked through `SKILL_DIR` under Node.
 * `src/ce-review-validator.ts` is the sole source; this generator bundles it
 * for Node and owns the committed bytes and their drift check.
 *
 * Usage:
 *   bun scripts/generate-ce-review-validator.ts         # Write the bundle
 *   bun scripts/generate-ce-review-validator.ts --check # Exit 1 on drift
 */
import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')

export const CE_REVIEW_VALIDATOR_RELATIVE_PATH =
  'skills/ce-review/scripts/validate-review.mjs'

const ENTRY_RELATIVE_PATH = 'src/ce-review-validator.ts'

// File-level Biome suppressions: this is a bundled artifact, so its internal
// style (assignment expressions, prototype builtins, import ordering) is the
// bundler's output, not hand-authored source. Formatting is applied below.
const GENERATED_BANNER = [
  '// biome-ignore-all lint: generated bundle',
  '// biome-ignore-all assist/source/organizeImports: generated bundle',
  '// Generated by scripts/generate-ce-review-validator.ts; do not edit by hand.',
  '// Run `bun run ce-review-validator:build` to regenerate.',
  '',
].join('\n')

/** Format the bundled JS through the repository's Biome config (via stdin). */
function formatJsWithBiome(content: string): string {
  const result = spawnSync(
    'bun',
    [
      'biome',
      'format',
      '--stdin-file-path=skills/ce-review/scripts/validate-review.mjs',
    ],
    { cwd: PROJECT_ROOT, input: content, encoding: 'utf8' },
  )
  if (result.status !== 0) {
    throw new Error(
      `biome format failed (exit ${result.status}): ${result.stderr || result.stdout}`,
    )
  }
  return result.stdout
}

/**
 * Bundle the shim entry for Node (ESM) and prepend the fixed provenance
 * banner. Bun's bundler inlines every non-builtin dependency, so the committed
 * file imports only Node builtins at execution time.
 */
export function generateValidatorContent(): string {
  const entryPath = path.join(PROJECT_ROOT, ENTRY_RELATIVE_PATH)
  const result = spawnSync(
    'bun',
    ['build', entryPath, '--target=node', '--format=esm'],
    {
      cwd: PROJECT_ROOT,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    },
  )
  if (result.status !== 0) {
    throw new Error(
      `bun build failed (exit ${result.status}): ${result.stderr || result.stdout}`,
    )
  }
  const body = result.stdout.replace(/\r\n?/g, '\n')
  const formatted = formatJsWithBiome(
    `${GENERATED_BANNER}${body.endsWith('\n') ? body : `${body}\n`}`,
  )
  return formatted.endsWith('\n') ? formatted : `${formatted}\n`
}

export function normalizeForCompare(content: string): string {
  return content.replace(/\r\n?/g, '\n')
}

/** Return a printable message for an unknown thrown value. */
function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function getValidatorPath(rootDir: string): string {
  return path.join(rootDir, CE_REVIEW_VALIDATOR_RELATIVE_PATH)
}

/** Write the generated bundle and return its absolute path. */
export function writeValidator(rootDir = PROJECT_ROOT): string {
  const targetPath = getValidatorPath(rootDir)
  fs.mkdirSync(path.dirname(targetPath), { recursive: true })
  fs.writeFileSync(targetPath, generateValidatorContent(), 'utf8')
  return targetPath
}

/** Compare the generated bundle with the committed artifact on disk. */
export function checkValidator(rootDir = PROJECT_ROOT): {
  ok: boolean
  message: string
} {
  const targetPath = getValidatorPath(rootDir)
  const displayPath = CE_REVIEW_VALIDATOR_RELATIVE_PATH

  if (!fs.existsSync(targetPath)) {
    return {
      ok: false,
      message: `${displayPath} does not exist. Run \`bun run ce-review-validator:build\` to create it.`,
    }
  }

  let existing: string
  try {
    existing = fs.readFileSync(targetPath, 'utf8')
  } catch (error) {
    return {
      ok: false,
      message: `${displayPath} could not be read: ${errorMessage(error)}`,
    }
  }

  if (
    normalizeForCompare(existing) !==
    normalizeForCompare(generateValidatorContent())
  ) {
    return {
      ok: false,
      message: `${displayPath} is out of date. Run \`bun run ce-review-validator:build\` to update it.`,
    }
  }

  return { ok: true, message: `${displayPath} is up to date.` }
}

function main(): void {
  if (process.argv.slice(2).includes('--check')) {
    const result = checkValidator()
    if (!result.ok) {
      console.error(`Error: ${result.message}`)
      process.exitCode = 1
      return
    }
    console.log(result.message)
    return
  }

  const targetPath = writeValidator()
  console.log(`Generated ${path.relative(PROJECT_ROOT, targetPath)}`)
}

if (import.meta.main) {
  try {
    main()
  } catch (error) {
    console.error(errorMessage(error))
    process.exitCode = 1
  }
}
