#!/usr/bin/env bun
/**
 * Generate the committed, self-contained Node-target validator shim under the
 * `ce:review` skill.
 *
 * The shim (`skills/ce-review/scripts/validate-review.mjs`) is a packaging
 * compatibility layer: shipped skill layouts cannot all rely on the npm CLI or
 * `dist/`, so the committed bundle is invoked through `SKILL_DIR` under Node.
 * `src/ce-review-validator.ts` is the sole source; this generator bundles it
 * for Node and owns the committed bytes and their drift check.
 *
 * `--check` verifies provenance -- that the committed bundle was generated
 * from the current sources (a digest over the entry's transitive relative
 * and dynamic imports, this generator's own content, and both the declared
 * range and actually-installed version of any external dependency it pulls
 * in) -- not byte equality of the bundle
 * itself. Byte equality would assert "this exact bundler and these exact
 * installed dependency versions emit these exact bytes today", which breaks
 * on unrelated Bun/dependency upgrades even when the source is current.
 * Execution correctness of the committed bundle is covered separately by
 * `tests/unit/ce-review-validator-packaging.test.ts`, which runs it under
 * real Node in three packaging layouts.
 *
 * Usage:
 *   bun scripts/generate-ce-review-validator.ts         # Write the bundle
 *   bun scripts/generate-ce-review-validator.ts --check # Exit 1 on drift
 */
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')

export const CE_REVIEW_VALIDATOR_RELATIVE_PATH =
  'skills/ce-review/scripts/validate-review.mjs'

const ENTRY_RELATIVE_PATH = 'src/ce-review-validator.ts'
const GENERATOR_RELATIVE_PATH = 'scripts/generate-ce-review-validator.ts'

const SHORT_DIGEST_LENGTH = 12

// File-level Biome suppressions: this is a bundled artifact, so its internal
// style (assignment expressions, prototype builtins, import ordering) is the
// bundler's output, not hand-authored source. Formatting is applied below.
const BANNER_LINES = [
  '// biome-ignore-all lint: generated bundle',
  '// biome-ignore-all assist/source/organizeImports: generated bundle',
  '// Generated by scripts/generate-ce-review-validator.ts; do not edit by hand.',
  '// Run `bun run ce-review-validator:build` to regenerate.',
]

const DIGEST_LINE_PATTERN = /^\/\/ source-digest: ([0-9a-f]{64})$/

/** Build the full generated-file banner, including the provenance digest line. */
function buildBanner(digest: string): string {
  return [...BANNER_LINES, `// source-digest: ${digest}`, ''].join('\n')
}

/**
 * Extract the stamped provenance digest from a committed bundle's banner.
 * Returns undefined if the banner is missing or malformed (any fixed banner
 * line absent, or no valid `source-digest:` line among the banner lines).
 */
function extractStampedDigest(content: string): string | undefined {
  const lines = content.split('\n')
  for (const bannerLine of BANNER_LINES) {
    if (!lines.includes(bannerLine)) {
      return undefined
    }
  }
  const headerLines = lines.slice(0, BANNER_LINES.length + 2)
  for (const line of headerLines) {
    const match = DIGEST_LINE_PATTERN.exec(line)
    if (match?.[1] !== undefined) {
      return match[1]
    }
  }
  return undefined
}

/** Format the bundled JS through the repository's Biome config (via stdin). */
function formatJsWithBiome(content: string): string {
  const result = spawnSync(
    'bun',
    [
      'biome',
      'format',
      '--stdin-file-path=skills/ce-review/scripts/validate-review.mjs',
    ],
    { cwd: PROJECT_ROOT, input: content, encoding: 'utf8' },
  )
  if (result.status !== 0) {
    throw new Error(
      `biome format failed (exit ${result.status}): ${result.stderr || result.stdout}`,
    )
  }
  return result.stdout
}

/**
 * Bundle the shim entry for Node (ESM) and prepend the fixed provenance
 * banner (with the given digest already stamped in). Bun's bundler inlines
 * every non-builtin dependency, so the committed file imports only Node
 * builtins at execution time.
 */
function bundleValidator(digest: string): string {
  const entryPath = path.join(PROJECT_ROOT, ENTRY_RELATIVE_PATH)
  const result = spawnSync(
    'bun',
    ['build', entryPath, '--target=node', '--format=esm'],
    {
      cwd: PROJECT_ROOT,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    },
  )
  if (result.status !== 0) {
    throw new Error(
      `bun build failed (exit ${result.status}): ${result.stderr || result.stdout}`,
    )
  }
  const body = result.stdout.replace(/\r\n?/g, '\n')
  const formatted = formatJsWithBiome(
    `${buildBanner(digest)}${body.endsWith('\n') ? body : `${body}\n`}`,
  )
  return formatted.endsWith('\n') ? formatted : `${formatted}\n`
}

/** Generate the bundle content, stamped with the current source-provenance digest. */
export function generateValidatorContent(rootDir = PROJECT_ROOT): string {
  return bundleValidator(computeSourceDigest(rootDir))
}

export function normalizeForCompare(content: string): string {
  return content.replace(/\r\n?/g, '\n')
}

/** Return a printable message for an unknown thrown value. */
function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function getValidatorPath(rootDir: string): string {
  return path.join(rootDir, CE_REVIEW_VALIDATOR_RELATIVE_PATH)
}

function sha256Hex(content: string): string {
  return createHash('sha256').update(normalizeForCompare(content)).digest('hex')
}

/**
 * Extract the module specifiers a source file references, through both
 * static `import`/`export ... from` statements and dynamic `import(...)`
 * calls with a literal string argument. Sufficient for this repository's
 * controlled source set -- every static import/export-from specifier in TS
 * source appears as `from '...'` or `from "..."`, including multi-line
 * named-import blocks, because Biome's enforced formatting keeps the `from`
 * clause and its string on one line; a dynamic import's literal argument is
 * similarly always `import('...')`/`import("...")` on one line under that
 * same formatting.
 *
 * This regex-over-text approach can, in principle, false-positive on a
 * comment or string literal that happens to contain `from '...'` or
 * `import('...')` text. That is not a silent gap for this gate: this
 * function only ever scans the validator entry's own transitive first-party
 * `.ts` files (never arbitrary or untrusted content), and a false-positive
 * match is handled loudly either way -- `resolveRelativeImport` throws if
 * the extracted text does not resolve to a real relative import target, and
 * if it coincidentally does resolve, the referenced file is simply
 * over-included in the digest (harmless for a staleness check). The failure
 * modes are "throw" or "over-include", never "silently miss".
 */
function extractImportSpecifiers(content: string): string[] {
  const specifiers: string[] = []
  const staticPattern = /\bfrom\s+(['"])([^'"]+)\1/g
  for (const match of content.matchAll(staticPattern)) {
    const specifier = match[2]
    if (specifier !== undefined) {
      specifiers.push(specifier)
    }
  }
  const dynamicPattern = /\bimport\s*\(\s*(['"])([^'"]+)\1/g
  for (const match of content.matchAll(dynamicPattern)) {
    const specifier = match[2]
    if (specifier !== undefined) {
      specifiers.push(specifier)
    }
  }
  return specifiers
}

/** Resolve a relative `./x.js`-style import specifier to its on-disk `.ts` source file. */
function resolveRelativeImport(fromFile: string, specifier: string): string {
  const resolved = path.resolve(path.dirname(fromFile), specifier)
  const candidates = resolved.endsWith('.js')
    ? [resolved.replace(/\.js$/, '.ts')]
    : [resolved, `${resolved}.ts`]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }
  throw new Error(
    `cannot resolve relative import "${specifier}" from ${path.relative(PROJECT_ROOT, fromFile)}`,
  )
}

interface SourceInputs {
  files: Set<string>
  externals: Set<string>
}

/**
 * Walk the transitive relative-import graph reachable from `entryPath`
 * (through both static `import`/`export ... from` and dynamic `import(...)`
 * calls -- see `extractImportSpecifiers`), collecting every reachable
 * repo-local `.ts` file and every bare (external) specifier encountered.
 * Bare specifiers and `node:` builtins are not followed.
 */
function collectSourceInputs(entryPath: string): SourceInputs {
  const files = new Set<string>()
  const externals = new Set<string>()
  const queue = [entryPath]

  while (queue.length > 0) {
    const currentFile = queue.pop()
    if (currentFile === undefined || files.has(currentFile)) {
      continue
    }
    files.add(currentFile)

    const content = fs.readFileSync(currentFile, 'utf8')
    for (const specifier of extractImportSpecifiers(content)) {
      if (specifier.startsWith('./') || specifier.startsWith('../')) {
        queue.push(resolveRelativeImport(currentFile, specifier))
      } else if (!specifier.startsWith('node:')) {
        externals.add(specifier)
      }
    }
  }

  return { files, externals }
}

interface PackageManifest {
  dependencies?: Record<string, string>
}

function readDeclaredDependencyRange(
  rootDir: string,
  specifier: string,
): string {
  const manifestPath = path.join(rootDir, 'package.json')
  const manifest = JSON.parse(
    fs.readFileSync(manifestPath, 'utf8'),
  ) as PackageManifest
  const range = manifest.dependencies?.[specifier]
  if (range === undefined) {
    throw new Error(
      `"${specifier}" is imported by the ce-review validator entry but is not declared in package.json dependencies`,
    )
  }
  return range
}

interface InstalledPackageManifest {
  version?: unknown
}

/**
 * Resolve the actually-installed version of an external dependency by
 * reading its on-disk `node_modules/<specifier>/package.json`. A declared
 * range (e.g. `^4.3.1`) does not capture a within-range resolution bump --
 * two installs satisfying the same range can ship different bytes -- so the
 * digest must key on what is actually installed, not the range. This reads
 * `node_modules` rather than parsing `bun.lock` because CI always runs
 * `bun install` before tests, making `node_modules` the deterministic,
 * already-resolved source of truth without a bespoke lockfile parser.
 * Throws loudly if the package is not installed rather than silently
 * falling back to the declared range, which would recreate the same
 * digest-blind-spot this function exists to close.
 */
function resolveInstalledDependencyVersion(
  rootDir: string,
  specifier: string,
): string {
  const manifestPath = path.join(
    rootDir,
    'node_modules',
    specifier,
    'package.json',
  )
  let raw: string
  try {
    raw = fs.readFileSync(manifestPath, 'utf8')
  } catch (error) {
    throw new Error(
      `cannot resolve the installed version of "${specifier}": ${manifestPath} could not be read (${errorMessage(error)}). Run \`bun install\`.`,
    )
  }
  const manifest = JSON.parse(raw) as InstalledPackageManifest
  if (typeof manifest.version !== 'string' || manifest.version.length === 0) {
    throw new Error(
      `cannot resolve the installed version of "${specifier}": ${manifestPath} has no valid "version" field`,
    )
  }
  return manifest.version
}

/**
 * Describe an external dependency for the digest as both its declared range
 * and its actually-installed version. Keeping both is strictly more
 * information than either alone: the declared range still changes the
 * digest when a contributor edits it (unchanged behavior), and the
 * installed version additionally changes the digest when a within-range
 * resolution bump changes the bundle's inlined contents.
 */
function describeExternalDependency(
  rootDir: string,
  specifier: string,
): string {
  const declaredRange = readDeclaredDependencyRange(rootDir, specifier)
  const installedVersion = resolveInstalledDependencyVersion(rootDir, specifier)
  return `${specifier}@${declaredRange}=>${installedVersion}`
}

/**
 * Compute the provenance digest for the validator bundle: a sha256 over a
 * canonical listing of every reachable source file's content hash, this
 * generator's own content, and every external dependency's declared range
 * plus its actually-installed version. Changing any input source file, the
 * generator itself, a dependency's declared range, or its resolved install
 * version changes the digest.
 */
export function computeSourceDigest(rootDir = PROJECT_ROOT): string {
  const entryPath = path.join(rootDir, ENTRY_RELATIVE_PATH)
  const generatorPath = path.join(rootDir, GENERATOR_RELATIVE_PATH)
  const { files, externals } = collectSourceInputs(entryPath)
  files.add(generatorPath)

  const fileLines = [...files]
    .map((filePath) => {
      const repoRelativePath = path.relative(rootDir, filePath)
      const hash = sha256Hex(fs.readFileSync(filePath, 'utf8'))
      return `${repoRelativePath} ${hash}`
    })
    .sort()

  const externalLines = [...externals]
    .map((specifier) => describeExternalDependency(rootDir, specifier))
    .sort()

  const canonical = [...fileLines, ...externalLines].join('\n')
  return createHash('sha256').update(canonical).digest('hex')
}

/** Write the generated bundle and return its absolute path. */
export function writeValidator(rootDir = PROJECT_ROOT): string {
  const targetPath = getValidatorPath(rootDir)
  fs.mkdirSync(path.dirname(targetPath), { recursive: true })
  fs.writeFileSync(targetPath, generateValidatorContent(rootDir), 'utf8')
  return targetPath
}

/**
 * Verify the committed bundle's provenance against the current sources.
 * Does not invoke `bun build` or `biome format` -- it only reads files and
 * hashes text, so it is fast and independent of the installed bundler
 * version.
 */
export function checkValidator(rootDir = PROJECT_ROOT): {
  ok: boolean
  message: string
} {
  const targetPath = getValidatorPath(rootDir)
  const displayPath = CE_REVIEW_VALIDATOR_RELATIVE_PATH

  if (!fs.existsSync(targetPath)) {
    return {
      ok: false,
      message: `${displayPath} does not exist. Run \`bun run ce-review-validator:build\` to create it.`,
    }
  }

  let existing: string
  try {
    existing = fs.readFileSync(targetPath, 'utf8')
  } catch (error) {
    return {
      ok: false,
      message: `${displayPath} could not be read: ${errorMessage(error)}`,
    }
  }

  const stampedDigest = extractStampedDigest(normalizeForCompare(existing))
  if (stampedDigest === undefined) {
    return {
      ok: false,
      message: `${displayPath} is missing its provenance header. Run \`bun run ce-review-validator:build\`.`,
    }
  }

  const expectedDigest = computeSourceDigest(rootDir)
  if (stampedDigest !== expectedDigest) {
    return {
      ok: false,
      message:
        `${displayPath} was generated from different sources ` +
        `(expected ${expectedDigest.slice(0, SHORT_DIGEST_LENGTH)}, found ${stampedDigest.slice(0, SHORT_DIGEST_LENGTH)}). ` +
        'Run `bun run ce-review-validator:build` to update it.',
    }
  }

  return { ok: true, message: `${displayPath} is up to date.` }
}

function main(): void {
  if (process.argv.slice(2).includes('--check')) {
    const result = checkValidator()
    if (!result.ok) {
      console.error(`Error: ${result.message}`)
      process.exitCode = 1
      return
    }
    console.log(result.message)
    return
  }

  const targetPath = writeValidator()
  console.log(`Generated ${path.relative(PROJECT_ROOT, targetPath)}`)
}

if (import.meta.main) {
  try {
    main()
  } catch (error) {
    console.error(errorMessage(error))
    process.exitCode = 1
  }
}
