// Provenance-digest proof for the `ce:review` validator bundle generator
// (`scripts/generate-ce-review-validator.ts`). `--check` (`checkValidator`)
// verifies that the committed bundle was generated from current sources by
// comparing a stamped `source-digest:` header against a freshly recomputed
// digest -- it does not compare bundle bytes, and it never shells out to
// `bun build` or `biome format` (only `writeValidator`'s bundling path does).
//
// Every test builds a small, self-contained fixture tree in its own temp
// directory; nothing here touches this repository's own sources or the
// committed `skills/ce-review/scripts/validate-review.mjs`.

import { describe, expect, test } from 'bun:test'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {
  CE_REVIEW_VALIDATOR_RELATIVE_PATH,
  checkValidator,
  computeSourceDigest,
} from '../../scripts/generate-ce-review-validator.ts'

const BANNER_LINES = [
  '// biome-ignore-all lint: generated bundle',
  '// biome-ignore-all assist/source/organizeImports: generated bundle',
  '// Generated by scripts/generate-ce-review-validator.ts; do not edit by hand.',
  '// Run `bun run ce-review-validator:build` to regenerate.',
]

const ZERO_DIGEST = '0'.repeat(64)

function makeTempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'generate-ce-review-validator-'))
}

/**
 * Write a fake installed-package `node_modules/<name>/package.json` so
 * `resolveInstalledDependencyVersion` can resolve it, mirroring a real
 * `bun install` layout closely enough for the digest to walk.
 */
function writeInstalledPackage(
  root: string,
  name: string,
  version: string,
): void {
  const dir = path.join(root, 'node_modules', name)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(
    path.join(dir, 'package.json'),
    `${JSON.stringify({ name, version }, null, 2)}\n`,
    'utf8',
  )
}

/**
 * Build a minimal, self-contained source tree matching the real repo's
 * shape closely enough for `computeSourceDigest`/`checkValidator` to walk:
 * an entry file with a relative import and a bare (external) import, a
 * transitive local dependency, a copy of the generator script, a
 * `package.json` declaring the external dependency's version range, and a
 * matching `node_modules/<name>/package.json` for its resolved version.
 */
function buildFixture(): string {
  const root = makeTempDir()
  fs.mkdirSync(path.join(root, 'src/lib'), { recursive: true })
  fs.mkdirSync(path.join(root, 'scripts'), { recursive: true })

  fs.writeFileSync(
    path.join(root, 'src/ce-review-validator.ts'),
    [
      "import type { z } from 'zod'",
      "import { helper } from './lib/helper.js'",
      '',
      'export function run(): string {',
      '  return helper()',
      '}',
      '',
    ].join('\n'),
    'utf8',
  )

  fs.writeFileSync(
    path.join(root, 'src/lib/helper.ts'),
    ['export function helper(): string {', "  return 'ok'", '}', ''].join('\n'),
    'utf8',
  )

  fs.writeFileSync(
    path.join(root, 'scripts/generate-ce-review-validator.ts'),
    [
      '// fixture copy of the generator; content only matters for hashing',
      '',
    ].join('\n'),
    'utf8',
  )

  fs.writeFileSync(
    path.join(root, 'package.json'),
    `${JSON.stringify({ dependencies: { zod: '4.6.2' } }, null, 2)}\n`,
    'utf8',
  )
  writeInstalledPackage(root, 'zod', '4.6.2')

  return root
}

function writeBundle(
  root: string,
  {
    digest,
    includeBanner = true,
  }: { digest?: string; includeBanner?: boolean },
): void {
  const targetPath = path.join(root, CE_REVIEW_VALIDATOR_RELATIVE_PATH)
  fs.mkdirSync(path.dirname(targetPath), { recursive: true })
  const lines = includeBanner ? [...BANNER_LINES] : []
  if (digest !== undefined) {
    lines.push(`// source-digest: ${digest}`)
  }
  lines.push('', 'export {}', '')
  fs.writeFileSync(targetPath, lines.join('\n'), 'utf8')
}

describe('computeSourceDigest', () => {
  test('is stable across repeated calls', () => {
    const root = buildFixture()
    expect(computeSourceDigest(root)).toBe(computeSourceDigest(root))
  })

  test('changes when a transitive source file is edited', () => {
    const root = buildFixture()
    const baseline = computeSourceDigest(root)

    fs.appendFileSync(
      path.join(root, 'src/lib/helper.ts'),
      '\nexport const extra = 1\n',
    )

    expect(computeSourceDigest(root)).not.toBe(baseline)
  })

  test('changes when the declared zod version in package.json changes', () => {
    const root = buildFixture()
    const baseline = computeSourceDigest(root)

    fs.writeFileSync(
      path.join(root, 'package.json'),
      `${JSON.stringify({ dependencies: { zod: '4.6.3' } }, null, 2)}\n`,
      'utf8',
    )

    expect(computeSourceDigest(root)).not.toBe(baseline)
  })

  test('changes when the generator script itself is edited', () => {
    const root = buildFixture()
    const baseline = computeSourceDigest(root)

    fs.appendFileSync(
      path.join(root, 'scripts/generate-ce-review-validator.ts'),
      '\n// a bundling-option comment that would change bundler output\n',
    )

    expect(computeSourceDigest(root)).not.toBe(baseline)
  })

  test('does not change when a file is added but unreachable from the entry', () => {
    const root = buildFixture()
    const baseline = computeSourceDigest(root)

    fs.writeFileSync(
      path.join(root, 'src/lib/unreachable.ts'),
      "export function unused(): string {\n  return 'never imported'\n}\n",
      'utf8',
    )

    expect(computeSourceDigest(root)).toBe(baseline)
  })

  test('changes when the installed dependency version differs from the declared range, even though the range itself is unchanged', () => {
    // `zod` is declared as `4.6.2` (exact) in buildFixture's package.json;
    // switch the fixture to a range declaration that a different installed
    // version still satisfies, to isolate "installed version differs" from
    // "declared range differs" (already covered above).
    const root = buildFixture()
    fs.writeFileSync(
      path.join(root, 'package.json'),
      `${JSON.stringify({ dependencies: { zod: '^4.6.0' } }, null, 2)}\n`,
      'utf8',
    )
    writeInstalledPackage(root, 'zod', '4.6.2')
    const baseline = computeSourceDigest(root)

    // A within-range resolution bump: the declared range `^4.6.0` still
    // matches `4.6.5`, but the installed bytes differ.
    writeInstalledPackage(root, 'zod', '4.6.5')

    expect(computeSourceDigest(root)).not.toBe(baseline)
  })

  test('throws a clear error instead of silently falling back to the declared range when a dependency is not installed', () => {
    const root = buildFixture()
    fs.rmSync(path.join(root, 'node_modules/zod'), {
      force: true,
      recursive: true,
    })

    expect(() => computeSourceDigest(root)).toThrow(
      /cannot resolve the installed version of "zod"/,
    )
  })

  test('includes a source file reachable only through a dynamic relative import() in the digest', () => {
    const root = buildFixture()
    fs.writeFileSync(
      path.join(root, 'src/lib/dynamic.ts'),
      "export function dynamicHelper(): string {\n  return 'dynamic'\n}\n",
      'utf8',
    )
    fs.appendFileSync(
      path.join(root, 'src/ce-review-validator.ts'),
      "\nexport async function loadDynamic() {\n  return import('./lib/dynamic.js')\n}\n",
    )
    const baseline = computeSourceDigest(root)

    fs.appendFileSync(
      path.join(root, 'src/lib/dynamic.ts'),
      '\nexport const extra = 1\n',
    )

    expect(computeSourceDigest(root)).not.toBe(baseline)
  })
})

describe('checkValidator', () => {
  test('passes for a bundle stamped with the current source digest', () => {
    const root = buildFixture()
    writeBundle(root, { digest: computeSourceDigest(root) })

    const result = checkValidator(root)

    expect(result.ok).toBe(true)
    expect(result.message).toContain(CE_REVIEW_VALIDATOR_RELATIVE_PATH)
  })

  test('fails with the provenance-header message when the digest line is stripped', () => {
    const root = buildFixture()
    writeBundle(root, { digest: undefined })

    const result = checkValidator(root)

    expect(result.ok).toBe(false)
    expect(result.message).toContain('missing its provenance header')
    expect(result.message).toContain(CE_REVIEW_VALIDATOR_RELATIVE_PATH)
  })

  test('fails with the provenance-header message when the whole banner is missing', () => {
    const root = buildFixture()
    writeBundle(root, {
      digest: computeSourceDigest(root),
      includeBanner: false,
    })

    const result = checkValidator(root)

    expect(result.ok).toBe(false)
    expect(result.message).toContain('missing its provenance header')
  })

  test('fails with the sources message when the stamped digest is altered', () => {
    const root = buildFixture()
    writeBundle(root, { digest: ZERO_DIGEST })

    const result = checkValidator(root)

    expect(result.ok).toBe(false)
    expect(result.message).toContain('generated from different sources')
    expect(result.message).toContain(CE_REVIEW_VALIDATOR_RELATIVE_PATH)
  })

  test('fails and names the path when the bundle does not exist', () => {
    const root = buildFixture()

    const result = checkValidator(root)

    expect(result.ok).toBe(false)
    expect(result.message).toContain('does not exist')
    expect(result.message).toContain(CE_REVIEW_VALIDATOR_RELATIVE_PATH)
  })

  test('does not shell out to bun build or biome format', () => {
    const root = buildFixture()
    writeBundle(root, { digest: computeSourceDigest(root) })

    // If checkValidator spawned `bun`/`biome`, clearing PATH would make the
    // spawn fail (ENOENT) and this call would throw instead of returning.
    const originalPath = process.env.PATH
    try {
      process.env.PATH = ''
      const result = checkValidator(root)
      expect(result.ok).toBe(true)
    } finally {
      process.env.PATH = originalPath
    }
  })
})
